
export const CREATE_MEMBERSHIP_REQUEST = "CREATE_MEMBERSHIP_REQUEST";
export const CREATE_MEMBERSHIP_SUCCESS = "CREATE_MEMBERSHIP_SUCCESS";
export const CREATE_MEMBERSHIP_FAILURE = "CREATE_MEMBERSHIP_FAILURE";

export const GET_MEMBERSHIP_REQUEST = 'GET_MEMBERSHIP_REQUEST';
export const GET_MEMBERSHIP_SUCCESS = 'GET_MEMBERSHIP_SUCCESS';
export const GET_MEMBERSHIP_FAILURE = 'GET_MEMBERSHIP_FAILURE';


export const UPDATE_MEMBERSHIP_REQUEST = 'UPDATE_MEMBERSHIP_REQUEST';
export const UPDATE_MEMBERSHIP_SUCCESS = 'UPDATE_MEMBERSHIP_SUCCESS';
export const UPDATE_MEMBERSHIP_FAILURE = 'UPDATE_MEMBERSHIP_FAILURE';

export const   DELETE_MEMBERSHIP_REQUEST = 'DELETE_MEMBERSHIP_REQUEST,';
export const   DELETE_MEMBERSHIP_SUCCESS = 'DELETE_MEMBERSHIP_SUCCESS,';
export const   DELETE_MEMBERSHIP_FAILURE = 'DELETE_MEMBERSHIP_FAILURE,';

export const GET_MEMBER_REQUEST = 'GET_MEMBER_REQUEST';
export const GET_MEMBER_SUCCESS = 'GET_MEMBER_SUCCESS';
export const GET_MEMBER_FAILURE = 'GET_MEMBER_FAILURE';

export const   DELETE_MEMBER_REQUEST = 'DELETE_MEMBER_REQUEST,';
export const   DELETE_MEMBER_SUCCESS = 'DELETE_MEMBER_SUCCESS,';
export const   DELETE_MEMBER_FAILURE = 'DELETE_MEMBER_FAILURE,';

export const GET_MONTHLYINCOME_REQUEST = 'GET_MONTHLYINCOME_REQUEST';
export const GET_MONTHLYINCOME_SUCCESS = 'GET_MONTHLYINCOME_SUCCESS';
export const GET_MONTHLYINCOME_FAILURE = 'GET_MONTHLYINCOME_FAILURE';

export const GET_MONTHLYINCOMECHART_REQUEST = 'GET_MONTHLYINCOMECHART_REQUEST';
export const GET_MONTHLYINCOMECHART_SUCCESS = 'GET_MONTHLYINCOMECHART_SUCCESS';
export const GET_MONTHLYINCOMECHART_FAILURE = 'GET_MONTHLYINCOMECHART_FAILURE';


export const CREATE_TRAINER_REQUEST = "CREATE_TRAINER_REQUEST";
export const CREATE_TRAINER_SUCCESS = "CREATE_TRAINER_SUCCESS";
export const CREATE_TRAINER_FAILURE = "CREATE_TRAINER_FAILURE";

export const    GET_TRAINER_REQUEST = "GET_TRAINER_REQUEST";
export const    GET_TRAINER_SUCCESS = "GET_TRAINER_SUCCESS";
export const    GET_TRAINER_FAILURE = "GET_TRAINER_FAILURE";


export const CLEAR_ERROR = "CLEAR_ERROR";