export const FETCH_MEMBER_REQUEST = 'FETCH_MEMBERSHIP_REQUEST';
export const FETCH_MEMBER_SUCCESS = 'FETCH_MEMBERSHIP_SUCCESS';
export const FETCH_MEMBER_FAILURE = 'FETCH_MEMBERSHIP_FAILURE';


export const CLEAR_ERROR = "CLEAR_ERROR"