export const FETCH_MEMBER_PRIVATE_REQUEST = 'FETCH_MEMBER_PRIVATE_REQUEST';
export const FETCH_MEMBER_PRIVATE_SUCCESS = 'FETCH_MEMBER_PRIVATE_SUCCESS';
export const FETCH_MEMBER_PRIVATE_FAILURE = 'FETCH_MEMBER_PRIVATE_FAILURE';

export const FETCH_MEMBER_PRIVATE_DIET_REQUEST = 'FETCH_MEMBER_PRIVATE_DIET_REQUEST';
export const FETCH_MEMBER_PRIVATE_DIET_SUCCESS = 'FETCH_MEMBER_PRIVATE_DIET_SUCCESS';
export const FETCH_MEMBER_PRIVATE_DIET_FAILURE = 'FETCH_MEMBER_PRIVATE_DIET_FAILURE';


export const CLEAR_ERROR = "CLEAR_ERROR"