export const CREATE_MEMBER_REQUEST = 'CREATE_MEMBER_REQUEST';
export const CREATE_MEMBER_SUCCESS = 'CREATE_MEMBER_SUCCESS';
export const CREATE_MEMBER_FAIL = 'CREATE_MEMBER_FAIL';

export const RENEW_MEMBER_REQUEST = 'RENEW_MEMBER_REQUEST';
export const RENEW_MEMBER_SUCCESS = 'RENEW_MEMBER_SUCCESS';
export const RENEW_MEMBER_FAIL =    'RENEW_MEMBER_FAIL';

export const FETCH_MEMBER_REQUEST = 'FETCH_MEMBER_REQUEST';
export const FETCH_MEMBER_SUCCESS = 'FETCH_MEMBER_SUCCESS';
export const FETCH_MEMBER_FAILURE = 'FETCH_MEMBER_FAILURE';



export const CLEAR_ERROR = "CLEAR_ERROR"