export const FETCH_TRAINER_DETAILS_REQUEST = 'FETCH_TRAINER_DETAILS_REQUEST';
export const FETCH_TRAINER_DETAILS_SUCCESS = 'FETCH_TRAINER_DETAILS_SUCCESS';
export const FETCH_TRAINER_DETAILS_FAILURE = 'FETCH_TRAINER_DETAILS_FAILURE';

export const GET_TRAINER_AMEMBER_REQUEST = 'GET_TRAINER_AMEMBER_REQUEST';
export const GET_TRAINER_AMEMBER_SUCCESS = 'GET_TRAINER_AMEMBER_SUCCESS';
export const GET_TRAINER_AMEMBER_FAILURE = 'GET_TRAINER_AMEMBER_FAILURE';

export const GET_PRIVATE_WORKOUT_REQUEST = 'GET_PRIVATE_WORKOUT_REQUEST';
export const GET_PRIVATE_WORKOUT_SUCCESS = 'GET_PRIVATE_WORKOUT_SUCCESS';
export const GET_PRIVATE_WORKOUT_FAILURE = 'GET_PRIVATE_WORKOUT_FAILURE';


export const CREATE_PRIVATE_WORKOUT_REQUEST = 'CREATE_PRIVATE_WORKOUT_REQUEST';
export const CREATE_PRIVATE_WORKOUT_SUCCESS = 'CREATE_PRIVATE_WORKOUT_SUCCESS';
export const CREATE_PRIVATE_WORKOUT_FAILURE = 'CREATE_PRIVATE_WORKOUT_FAILURE';

export const DELETE_PRIVATE_WORKOUT_REQUEST = 'DELETE_PRIVATE_WORKOUT_REQUEST';
export const DELETE_PRIVATE_WORKOUT_SUCCESS = 'DELETE_PRIVATE_WORKOUT_SUCCESS';
export const DELETE_PRIVATE_WORKOUT_FAILURE = 'DELETE_PRIVATE_WORKOUT_FAILURE';

export const GET_TRAINER_SCHEDULE_REQUEST = 'GET_TRAINER_SCHEDULE_REQUEST';
export const GET_TRAINER_SCHEDULE_SUCCESS = 'GET_TRAINER_SCHEDULE_SUCCESS';
export const GET_TRAINER_SCHEDULE_FAILURE = 'GET_TRAINER_SCHEDULE_FAILURE';

export const CREATE_TRAINER_SCHEDULE_REQUEST = 'CREATE_TRAINER_SCHEDULE_REQUEST';
export const CREATE_TRAINER_SCHEDULE_SUCCESS = 'CREATE_TRAINER_SCHEDULE_SUCCESS';
export const CREATE_TRAINER_SCHEDULE_FAILURE = 'CREATE_TRAINER_SCHEDULE_FAILURE';

export const UPDATE_TRAINER_SCHEDULE_REQUEST = 'UPDATE_TRAINER_SCHEDULE_REQUEST';
export const UPDATE_TRAINER_SCHEDULE_SUCCESS = 'UPDATE_TRAINER_SCHEDULE_SUCCESS';
export const UPDATE_TRAINER_SCHEDULE_FAILURE = 'UPDATE_TRAINER_SCHEDULE_FAILURE';

export const DELETE_TRAINER_SCHEDULE_REQUEST = 'DELETE_TRAINER_SCHEDULE_REQUEST';
export const DELETE_TRAINER_SCHEDULE_SUCCESS = 'DELETE_TRAINER_SCHEDULE_SUCCESS';
export const DELETE_TRAINER_SCHEDULE_FAILURE = 'DELETE_TRAINER_SCHEDULE_FAILURE';



export const GET_PRIVATE_DIET_REQUEST = 'GET_PRIVATE_DIET_REQUEST';
export const GET_PRIVATE_DIET_SUCCESS = 'GET_PRIVATE_DIET_SUCCESS';
export const GET_PRIVATE_DIET_FAILURE = 'GET_PRIVATE_DIET_FAILURE';

export const GET_COUNT_REQUEST = 'GET_COUNT_REQUEST';
export const GET_COUNT_SUCCESS = 'GET_COUNT_SUCCESS';
export const GET_COUNT_FAILURE = 'GET_COUNT_FAILURE';


export const CREATE_PRIVATE_DIET_REQUEST = 'CREATE_PRIVATE_DIET_REQUEST';
export const CREATE_PRIVATE_DIET_SUCCESS = 'CREATE_PRIVATE_DIET_SUCCESS';
export const CREATE_PRIVATE_DIET_FAILURE = 'CREATE_PRIVATE_DIET_FAILURE';

export const DELETE_PRIVATE_DIET_REQUEST = 'DELETE_PRIVATE_DIET_REQUEST';
export const DELETE_PRIVATE_DIET_SUCCESS = 'DELETE_PRIVATE_DIET_SUCCESS';
export const DELETE_PRIVATE_DIET_FAILURE = 'DELETE_PRIVATE_DIET_FAILURE';


export const CLEAR_ERROR = "CLEAR_ERROR"